spring.datasource.url: jdbc:h2:file:./camunda-h2-database
#Enabled for authorization
camunda.bpm:
  authorization:
    enabled: true
# This is boot admin user
  admin-user:
    id: amar.deep.singh@xyz.com
    firstName: Amar Deep
    lastName: Singh
    email: amar.deep.singh@xyz.com
  filter:
    create: All tasks
  generic-properties:
    properties:
      generalResourceWhitelistPattern: ".+"
spring:
  security:
    saml2:
      relyingparty:
        registration:
          camunda:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            decryption:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            assertingparty:
              metadata-uri: "classpath:okta-metadata.xml"

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.saml: TRACE
    org.opensaml.xmlsec: TRACE