spring.datasource.url: jdbc:h2:file:./camunda-h2-database

server:
  port: 8080
#Enabled for authorization
camunda.bpm:
  authorization:
    enabled: true
# This is boot user for first time and you can delete it later
  admin-user:
    id: demo
    password: demo
  #    enabled-for-custom-code: true
  filter:
    create: All tasks
spring:
  security:
    saml2:
      relyingparty:
        registration:
          camunda:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            decryption:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            identityprovider:
              metadata-uri: "classpath:okta-metadata.xml"
okta:
  issuer:
    url: https://your.dev.tenant.okta.com
# The value of this flag activates single logout (clears okta session as well.)
sso:
  enable:
    singlelogout: false

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.saml: TRACE
    org.opensaml.xmlsec: TRACE